# Generated by Django 4.1.7 on 2023-03-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=100)),
                ('lastName', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['lastName'],
            },
        ),
    ]
